name: CI

on:
  push:
    branches:
      - main
      - build-system-rewrite
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex libfl-dev
          sudo apt-get install -y libgtest-dev cmake

      - name: Install Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build project
        run: |
          mkdir -p build
          cmake -S ./ -B build -DCMAKE_BUILD_TYPE=Release -DPRINT_TABLE=ON
          cmake --build build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/
          if-no-files-found: error

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: Run unit tests table
        run: |
          chmod +x build/tests/UnitTestTable 
          ./build/tests/UnitTestTable 

      - name: Run unit tests tree
        run: |
          chmod +x build/tests/UnitTestTree
          ./build/tests/UnitTestTree
