name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex libfl-dev
          sudo apt-get install -y libgtest-dev cmake

      - name: Install Google Test
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build unit tests table
        run: |
          mkdir -p test/table_test/build
          cmake -S ./ -B build/Release -DCMAKE_BUILD_TYPE=Release
          cmake --build build/Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            test/table_test/build

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: test/table_test

      - name: Run unit tests
        run: |
          chmod +x test/table_test/build/Release/UnitTestTable
          .test/table_test/build/Release/UnitTestTable